[config.wallpaper]
# Whether to set the wallpaper or not
set = false 

# The base command to run for applying the wallpaper, shouldn't have spaces in it.
command = "swww"

# The arguments that will be provided to the command.
# Keywords like {{ mode }} or anything that works inside of hooks doesn't work here.
# The last argument will be the image path.
arguments = ["img", "--transition-type", "center"]

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""


[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-color.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = 'hyprctl reload'


[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/waybar/scripts/launch.sh'


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/colors.rasi'

[templates.bash]
input_path = '~/.config/matugen/templates/shell.json'
output_path = '~/.config/matugen/shell/colors.json'
post_hook = '~/.config/hypr/scripts/keyboradColor.sh'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'
